# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java-CI-with-Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-java:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew build
    
  ci-process:
    
    runs-on: ubuntu-latest
    
    needs: [build-java]
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-central-1
    
    #- name: Creating elasticbeanstalk
    #  run : aws elasticbeanstalk create-application --application-name app-java
    
    - name: Creating environment
      run : aws elasticbeanstalk create-environment --application-name app-java \
            --environment-name staging \
            --solution-stack-name "64bit Amazon Linux 2017.09 v2.9.2 running Docker 17.12.0-ce" \
            --option-settings file://options.json
   
   
   
    #- name: Copy files to the S3 with the AWS CLI
    #  run: |
    #    aws s3 sync . s3://java-app-github-actions/Garbage


  # - name: Check current directory
   #   run : ls -la
    
   # - name: Build Docker image
   #   run : docker build -t java-app .
    
   # - name: Check image
   #   run : docker images
    
  #  - name: Build and Push Docker Image
  #    uses: mr-smithers-excellent/docker-build-push@v4
  #    with:
  #      image: daniilnedostup/java-app
  #      registry: docker.io
  #      username: daniilnedostup
  #      password: 23mtk456
      
      
    #- name: Build and Push Docker Image
    #  uses: mr-smithers-excellent/docker-build-push@v4
    #  with:
     #   image: nanajanashia/demo-app
    #    registry: docker.io
    #    username: ${{ secrets.DOCKER_USERNAME }}
    #    password: ${{ secrets.DOCKER_PASSWORD }}
         
